package springMVC.model;
// Generated 2021�~1��28�� �W��1:29:10 by Hibernate Tools 5.4.21.Final

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Receipt generated by hbm2java
 */
@Entity
@Table(name = "receipt")
public class Receipt implements java.io.Serializable {

	private String time;
	private String number1;
	private String number2;
	private String number3;
	private String special1;
	private String special2;
	private String spe6num1;
	private String spe6num2;
	private String spe6num3;

	public Receipt() {
	}

	public Receipt(String time, String number1, String number2, String number3, String special1, String special2) {
		this.time = time;
		this.number1 = number1;
		this.number2 = number2;
		this.number3 = number3;
		this.special1 = special1;
		this.special2 = special2;
	}

	public Receipt(String time, String number1, String number2, String number3, String special1, String special2,
			String spe6num1, String spe6num2, String spe6num3) {
		this.time = time;
		this.number1 = number1;
		this.number2 = number2;
		this.number3 = number3;
		this.special1 = special1;
		this.special2 = special2;
		this.spe6num1 = spe6num1;
		this.spe6num2 = spe6num2;
		this.spe6num3 = spe6num3;
	}

	@Id
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getNumber1() {
		return this.number1;
	}

	public void setNumber1(String number1) {
		this.number1 = number1;
	}

	public String getNumber2() {
		return this.number2;
	}

	public void setNumber2(String number2) {
		this.number2 = number2;
	}

	public String getNumber3() {
		return this.number3;
	}

	public void setNumber3(String number3) {
		this.number3 = number3;
	}

	public String getSpecial1() {
		return this.special1;
	}

	public void setSpecial1(String special1) {
		this.special1 = special1;
	}

	public String getSpecial2() {
		return this.special2;
	}

	public void setSpecial2(String special2) {
		this.special2 = special2;
	}

	public String getSpe6num1() {
		return this.spe6num1;
	}

	public void setSpe6num1(String spe6num1) {
		this.spe6num1 = spe6num1;
	}

	public String getSpe6num2() {
		return this.spe6num2;
	}

	public void setSpe6num2(String spe6num2) {
		this.spe6num2 = spe6num2;
	}

	public String getSpe6num3() {
		return this.spe6num3;
	}

	public void setSpe6num3(String spe6num3) {
		this.spe6num3 = spe6num3;
	}

}
